# Generated by Django 2.2.5 on 2019-09-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProPlayer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('steam_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('avatar', models.ImageField(default='avatars/none.png', unique=True, upload_to='avatars')),
            ],
        ),
        migrations.CreateModel(
            name='HeroData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('kills', models.FloatField()),
                ('deaths', models.FloatField()),
                ('assists', models.FloatField()),
                ('GPM', models.FloatField()),
                ('XPM', models.FloatField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Hero')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.ProPlayer')),
            ],
        ),
    ]
