# Generated by Django 3.0a1 on 2019-09-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20190927_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herodata',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.HeroDotaBuff'),
        ),
    ]
