# Generated by Django 3.0a1 on 2019-09-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_cmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='herodata',
            name='win_rate',
        ),
        migrations.AlterField(
            model_name='herodata',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Hero'),
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.GameMode')),
                ('lobby_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Lobby')),
            ],
        ),
    ]
