# Generated by Django 3.0a1 on 2019-09-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_auto_20190929_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='game_mode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='lobby_type',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='GameMode',
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
    ]
