# Generated by Django 3.0a1 on 2019-09-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_auto_20190929_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Hero')),
            ],
        ),
    ]
