# Generated by Django 3.0a1 on 2019-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_simplematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmatch',
            name='player_id',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='simplematch',
            name='player_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
